#!/usr/bin/env python3
"""Generate supabase/seed.sql from the reviewable data files in scripts/data/.

Inputs : courses.tsv, courses_grad.tsv, faculty.tsv, history_sections.csv
Output : supabase/seed.sql   (idempotent; safe to re-run)
"""
import csv, json, os, re, sys, unicodedata

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, 'scripts', 'data')
OUT  = os.path.join(ROOT, 'supabase', 'seed.sql')

def q(v):
    """SQL literal."""
    if v is None or v == '': return 'null'
    return "'" + str(v).replace("'", "''") + "'"

def arr(xs):
    return "'{" + ",".join(str(x) for x in xs) + "}'" if xs else "'{}'"

def tsv(name):
    with open(os.path.join(DATA, name), encoding='utf-8') as f:
        return list(csv.DictReader(f, delimiter='\t'))

# ----------------------------------------------------------------- times ----
DAY_MAP = {'M':1,'T':2,'W':3,'Th':4,'F':5,'S':6,'Su':7}

def parse_days(pat):
    out, i = [], 0
    while i < len(pat):
        if pat[i:i+2] in ('Th','Su'):
            out.append(DAY_MAP[pat[i:i+2]]); i += 2
        elif pat[i] in DAY_MAP:
            out.append(DAY_MAP[pat[i]]); i += 1
        else:
            i += 1
    return out

def parse_time_range(tok):
    """UW format: '845-1045', '1100-100', '545-745P'.
    A trailing P marks the whole range PM; otherwise hours 8-11 are AM and
    hours 12 and 1-7 are PM."""
    pm_all = tok.endswith('P')
    a, b = tok.rstrip('P').split('-')
    def one(t):
        t = t.zfill(3)
        h, m = int(t[:-2]), int(t[-2:])
        if pm_all:
            if h != 12: h += 12
        elif 8 <= h <= 11:
            pass                      # AM as written
        elif h != 12:
            h += 12                   # 1-7 -> PM
        return f"{h:02d}:{m:02d}:00"
    return one(a), one(b)

# ------------------------------------------------------------ name match ----
ALIASES = {
    'dame,steve':'Stephen Dame', 'nixon,david':'David Nixon',
    'rubin,zak':'Zachary Rubin', 'wang,joanna':'Zhao Wang',
    'melnikoff,steven oscar':'Steve Melnikoff', 'carr,matt':'Matthew Carr',
    'thamilarasu,geetha':'Geethapriya Thamilarasu',
    'parsons,erika':'Erika F. Parsons', 'folsom,tyler':'Tyler C. Folsom',
    'gruenbaum,peter e':'Peter Gruenbaum',
}

def norm(s):
    s = unicodedata.normalize('NFKD', s).encode('ascii','ignore').decode()
    return re.sub(r'[^a-z, ]', '', s.lower()).strip()

def split_sched(name):
    """'Kool,Nancy L.' -> ('kool', 'nancy')"""
    last, _, first = name.partition(',')
    return norm(last).strip(), norm(first).strip().split(' ')[0] if first else ''

faculty = tsv('faculty.tsv')
by_key = {}
for f in faculty:
    parts = f['full_name'].split()
    by_key[(norm(parts[-1]), norm(parts[0]))] = f['full_name']

def resolve(sched_name):
    k = norm(sched_name).replace(' ,', ',')
    if k in ALIASES: return ALIASES[k], True
    last, first = split_sched(sched_name)
    if (last, first) in by_key: return by_key[(last, first)], True
    # fall back to unique last-name match
    cands = [v for (l, fi), v in by_key.items() if l == last]
    if len(cands) == 1: return cands[0], True
    # unknown: rebuild as "First Last" for a new instructor record
    l2, _, f2 = sched_name.partition(',')
    return f"{f2.strip()} {l2.strip()}".title().strip(), False

# ------------------------------------------------------------ build SQL ----
L = []
w = L.append
w("-- GENERATED by scripts/generate_seed.py -- do not edit by hand.")
w("-- Re-run: python3 scripts/generate_seed.py")
w("begin;")
w("")

# --- access control -------------------------------------------------------
w("insert into allowed_email_domains (domain) values ('uw.edu')")
w("  on conflict (domain) do nothing;")
# Anyone listed here is granted the coordinator role on first sign-in.
w("insert into bootstrap_coordinators (email, note) values")
w("  ('minchen2@uw.edu', 'CSS teaching coordinator'),")
w("  ('geetha@uw.edu',   'Department chair'),")
w("  ('pisan@uw.edu',    'Maintainer')")
w("  on conflict (email) do nothing;")
w("")
w("-- handle_new_user only reads this list at first sign-in, so adding someone")
w("-- afterwards would not reach an account that already exists. This keeps the")
w("-- list authoritative. It only ever promotes; nobody is demoted here.")
w("update profiles p set role = 'coordinator'")
w("  from bootstrap_coordinators b")
w(" where b.email = p.email and p.role <> 'coordinator';")
w("")

# --- academic years / terms ----------------------------------------------
w("insert into academic_years (name, start_year, is_current) values")
w("  ('2025-26', 2025, false), ('2026-27', 2026, true)")
w("  on conflict (name) do nothing;")
w("insert into terms (academic_year_id, quarter, sort_order)")
w("select ay.id, t.q::quarter, t.o from academic_years ay,")
w("  (values ('autumn',1),('winter',2),('spring',3)) as t(q,o)")
w("  on conflict (academic_year_id, quarter) do nothing;")
w("")

# --- buildings ------------------------------------------------------------
BUILDINGS = [('UW1','UW Bothell UW1'), ('UW2','UW Bothell UW2'),
             ('UWBB','Husky Hall / UWBB'), ('INV','Innovation Hall'),
             ('LBA','Library Annex'), ('DISC','Discovery Hall'),
             ('ARC','Activities and Recreation Center')]
w("insert into buildings (code, name) values")
w(",\n".join(f"  ({q(c)}, {q(n)})" for c, n in BUILDINGS))
w("  on conflict (code) do nothing;")
w("")

# --- time slots: the real UW Bothell grid --------------------------------
BLOCKS = [('845-1045','8:45–10:45 AM'), ('1100-100','11:00 AM–1:00 PM'),
          ('115-315','1:15–3:15 PM'), ('330-530','3:30–5:30 PM'),
          ('545-745P','5:45–7:45 PM'), ('800-1000P','8:00–10:00 PM')]
rows, order = [], 0
for pat, standard in [('MW',True),('TTh',True),('M',False),('T',False),
                      ('W',False),('Th',False),('F',False)]:
    for tok, pretty in BLOCKS:
        order += 1
        st, en = parse_time_range(tok)
        rows.append(f"  ({q(pat + ' ' + pretty)}, {q(pat)}, {arr(parse_days(pat))}, "
                    f"{q(st)}, {q(en)}, {str(standard).lower()}, {order})")
w("insert into time_slots (label, day_pattern, days, start_time, end_time, is_standard, sort_order) values")
w(",\n".join(rows))
w("  on conflict (day_pattern, start_time, end_time) do nothing;")
w("")

# --- courses --------------------------------------------------------------
def course_rows(recs, level, active):
    out = []
    for r in recs:
        out.append(f"  ('CSS', {int(r['number'])}, {q(r['title'])}, "
                   f"{r['credits_min']}, {r['credits_max']}, {q(level)}, "
                   f"{q(r['prereq_text'])}, {str(active).lower()})")
    return out

ug = tsv('courses.tsv'); gr = tsv('courses_grad.tsv')
w("insert into courses (subject, number, title, credits_min, credits_max, level, prereq_text, is_active) values")
w(",\n".join(course_rows(ug, 'undergraduate', True) +
             course_rows(gr, 'graduate', False)))
w("  on conflict (subject, number) do nothing;")
w("")

# --- instructors ----------------------------------------------------------
# Annual course baselines before any teaching release: 8 on the teaching
# track, 5 on the tenure track. Per-course hires (affiliate, part-time) and
# emeriti carry no annual obligation, so they get null rather than zero.
# Null means 'no target set', which the conflict engine skips entirely.
TEACHING_TRACK_BASE = 8
TENURE_TRACK_BASE   = 5

def base_load(rank, cat):
    if cat in ('affiliate', 'part_time', 'emeritus', 'other'):
        return 'null'
    r = rank.lower()
    # Checked first: 'Associate Teaching Professor' must not fall through to
    # the tenure-track branch just because it ends in 'Professor'.
    if 'teaching professor' in r or 'lecturer' in r:
        return str(TEACHING_TRACK_BASE)
    if 'professor' in r:
        return str(TENURE_TRACK_BASE)
    return 'null'

hist = list(csv.DictReader(open(os.path.join(DATA,'history_sections.csv'))))
sched_names = sorted({h['instructor'] for h in hist if h['instructor']})
resolved, extra = {}, []
known = {f['full_name'] for f in faculty}
for sn in sched_names:
    name, matched = resolve(sn)
    resolved[sn] = name
    if not matched and name not in known:
        extra.append(name); known.add(name)

irows = []
for f in faculty:
    parts = f['full_name'].split()
    irows.append(f"  ({q(f['full_name'])}, {q(parts[0])}, {q(parts[-1])}, {q(f['email'])}, "
                 f"{q(f['rank'])}, {q(f['category'])}, "
                 f"{str(f['category'] != 'emeritus').lower()}, {base_load(f['rank'], f['category'])})")
for n in sorted(set(extra)):
    parts = n.split()
    irows.append(f"  ({q(n)}, {q(parts[0])}, {q(parts[-1])}, null, "
                 f"{q('Instructor (from time schedule)')}, 'other', true, null)")
w("-- Roster = CSS faculty directory + anyone who appears in the imported")
w("-- time schedules but is not listed on the directory page.")
w("insert into instructors (full_name, first_name, last_name, email, rank, category, is_active, base_annual_courses) values")
w(",\n".join(irows))
w("  on conflict (full_name) do nothing;")
w("")
# --- teaching history -----------------------------------------------------
def modality_for(row, meetings):
    rooms = [m[2] for m in meetings]
    online = [r for r in rooms if r.startswith('*')]
    if meetings and len(online) == len(meetings): return 'online_sync'
    if online:                                    return 'hybrid'
    if not meetings:                              return None
    return 'in_person'

TERM_LABEL = {'autumn':'autumn','winter':'winter','spring':'spring'}
hrows = []
for h in hist:
    if not h['instructor']:
        continue                       # independent study etc. — nobody listed
    meetings = json.loads(h['meetings'])
    first = meetings[0] if meetings else None
    days = parse_days(first[0]) if first else []
    st, en = parse_time_range(first[1]) if first else (None, None)
    room = first[2] if first and not first[2].startswith('*') else None
    hrows.append(
        f"  ({q(resolved[h['instructor']])}, {q(h['instructor'])}, {int(h['course'])}, "
        f"{q('CSS ' + h['course'])}, {q(h['academic_year'])}, {q(h['quarter'])}, "
        f"{q(h['section'])}, {q(h['sln'])}, {arr(days)}, {q(st)}, {q(en)}, {q(room)}, "
        f"{h['enrl'] or 'null'}, {(h['limit'] or '').rstrip('ABCDEFGHIJKLMNOPQRSTUVWXYZ') or 'null'}, "
        f"{q(modality_for(h, meetings))})")

w("-- Imported from past-course-schedules/*.pdf (AUT2025, WIN2026, SPR2026).")
w("create temp table _hist (")
w("  instructor_name text, instructor_raw text, course_num int, course_code text,")
w("  academic_year text, quarter text, section_letter text, sln text,")
w("  days smallint[], start_time time, end_time time, room_label text,")
w("  enrollment int, enrollment_cap int, modality text) on commit drop;")
w("insert into _hist values")
w(",\n".join(hrows) + ";")
w("")
w("insert into teaching_history (instructor_id, instructor_name_raw, course_id,")
w("  course_code_raw, academic_year, quarter, section_letter, sln, days,")
w("  start_time, end_time, room_label, enrollment, enrollment_cap, modality)")
w("select i.id, h.instructor_raw, c.id, h.course_code, h.academic_year,")
w("       h.quarter::quarter, h.section_letter, h.sln, h.days, h.start_time,")
w("       h.end_time, h.room_label, h.enrollment, h.enrollment_cap, h.modality::modality")
w("from _hist h")
w("left join instructors i on i.full_name = h.instructor_name")
w("left join courses c on c.subject = 'CSS' and c.number = h.course_num")
w("on conflict (academic_year, quarter, sln, section_letter) do nothing;")
w("")
w("-- Anyone who has taught a course is presumed qualified to teach it again.")
w("insert into instructor_qualifications (instructor_id, course_id, source)")
w("select distinct th.instructor_id, th.course_id, 'history'::qualification_source")
w("from teaching_history th")
w("where th.instructor_id is not null and th.course_id is not null")
w("on conflict (instructor_id, course_id) do nothing;")
w("")
w("commit;")
w("")

with open(OUT, 'w', encoding='utf-8') as f:
    f.write("\n".join(L))

print(f"wrote {OUT}")
print(f"  courses      : {len(ug)} undergraduate + {len(gr)} graduate")
print(f"  time_slots   : {len(rows)}")
print(f"  instructors  : {len(faculty)} from directory + {len(set(extra))} schedule-only")
print(f"  history rows : {len(hrows)}")
if extra:
    print("\n  schedule-only instructors (no directory entry, no email):")
    for n in sorted(set(extra)): print(f"    - {n}")
